---
project_name: terraputs
before:
  hooks:
    - make test
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./main.go
archives:
  - wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
dockers:
  - image_templates:
      - "clapclapexcitement/{{.ProjectName}}:latest"
      - "clapclapexcitement/{{.ProjectName}}:{{.Version}}"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
  - image_templates:
      - "clapclapexcitement/{{.ProjectName}}:latest-arm64"
      - "clapclapexcitement/{{.ProjectName}}:{{.Version}}-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    goarch: arm64
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
