---
name: CI/CD

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      # While not actually (currently) used in snapshot-building, logging in to
      # DockerHub on non-main builds vets DockerHub login problems in advance of
      # a merge to main.
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: clapclapexcitement
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: make
      - name: Ensure unique version
        run: make check-tag

  build-and-publish-release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-snapshot
    environment:
      name: release
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: clapclapexcitement
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create release tag
        run: make tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
